#!/bin/bash

# Check if arguments are passed
if [ "$#" -ne 2 ]; then
    echo "Usage: ./runner <hotel_ids> <destination_ids>"
    exit 1
fi

# Execute the hotelMerger.js script with provided arguments
node hotelMerger.js "$1" "$2"
